# Model Building using Pandas

## importing libs

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## setting flags

In [ ]:
pd.options.display.max_columns=500
pd.options.display.max_rows=200
# to set dataframes to show more cols & rows

## setting path

In [ ]:
# from google.colab import files
# uploaded = files.upload()

# import os
# os.chdir('content/drive/MyDrive/PG-DBDA C-DAC Mumbai KH/Final Project/US accident/Datasets')
# os.getcwd()
# Presentation_output.csv

import os
os.chdir(r'E:\Datasets\US Accidents (2016 - 2023)')
os.getcwd()

'E:\\Datasets\\US Accidents (2016 - 2023)'

## importing dataset

In [ ]:
df_mod = pd.read_csv('Presentation_output.csv')

In [ ]:
df_mod.shape

(3414595, 11)

In [ ]:
df_mod.head()

Zipcode  Temperature  Weekday  Month  Hour   Latitude  Longitude  Humidity  \
0    43017         42.1        1      2     0  40.108910 -83.092860      58.0   
1    45217         37.0        1      2     7  39.172393 -84.492792      93.0   
2    45216         33.8        1      2    15  39.192880 -84.477230     100.0   
3    44113         33.1        1      2    17  41.473900 -81.704233      96.0   
4    45335         33.8        1      2    17  39.582242 -83.677814      93.0   

   Crossings  Weather_condition  Severity  
0      False                  6         3  
1      False                  6         3  
2      False                  7         2  
3      False                  7         2  
4      False                  7         2

In [ ]:
df_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3414595 entries, 0 to 3414594
Data columns (total 11 columns):
 #   Column             Dtype  
---  ------             -----  
 0   Zipcode            int64  
 1   Temperature        float64
 2   Weekday            int64  
 3   Month              int64  
 4   Hour               int64  
 5   Latitude           float64
 6   Longitude          float64
 7   Humidity           float64
 8   Crossings          bool   
 9   Weather_condition  int64  
 10  Severity           int64  
dtypes: bool(1), float64(4), int64(6)
memory usage: 263.8 MB


In [ ]:
df_mod.describe()

Zipcode   Temperature       Weekday         Month          Hour  \
count  3.414595e+06  3.414595e+06  3.414595e+06  3.414595e+06  3.414595e+06   
mean   5.541283e+04  6.144015e+01  3.138422e+00  6.746069e+00  1.285166e+01   
std    3.130264e+04  1.910535e+01  1.868596e+00  3.789734e+00  5.784718e+00   
min    1.001000e+03 -4.500000e+01  0.000000e+00  1.000000e+00  0.000000e+00   
25%    2.920900e+04  4.900000e+01  2.000000e+00  3.000000e+00  8.000000e+00   
50%    4.850700e+04  6.300000e+01  3.000000e+00  7.000000e+00  1.400000e+01   
75%    9.130200e+04  7.600000e+01  5.000000e+00  1.000000e+01  1.700000e+01   
max    9.940100e+04  1.960000e+02  6.000000e+00  1.200000e+01  2.300000e+01   

           Latitude     Longitude      Humidity  Weather_condition  \
count  3.414595e+06  3.414595e+06  3.414595e+06       3.414595e+06   
mean   3.606361e+01 -9.537304e+01  6.324460e+01       3.117601e+00   
std    5.315566e+00  1.807716e+01  2.287674e+01       3.407398e+00   
min    2.456603e+01 -1.245481e+02  1.000000e+00       0.000000e+00   
25%    3.317705e+01 -1.176453e+02  4.700000e+01       1.000000e+00   
50%    3.589800e+01 -8.749843e+01  6.500000e+01       1.000000e+00   
75%    4.007191e+01 -8.021342e+01  8.200000e+01       7.000000e+00   
max    4.900058e+01 -6.748413e+01  1.000000e+02       1.100000e+01   

           Severity  
count  3.414595e+06  
mean   2.073957e+00  
std    3.816288e-01  
min    1.000000e+00  
25%    2.000000e+00  
50%    2.000000e+00  
75%    2.000000e+00  
max    4.000000e+00

## identify Predictors (X) & Response(Y)

In [ ]:
x = df_mod.drop('Severity', axis=1)
x[:5]

Zipcode  Temperature  Weekday  Month  Hour   Latitude  Longitude  Humidity  \
0    43017         42.1        1      2     0  40.108910 -83.092860      58.0   
1    45217         37.0        1      2     7  39.172393 -84.492792      93.0   
2    45216         33.8        1      2    15  39.192880 -84.477230     100.0   
3    44113         33.1        1      2    17  41.473900 -81.704233      96.0   
4    45335         33.8        1      2    17  39.582242 -83.677814      93.0   

   Crossings  Weather_condition  
0      False                  6  
1      False                  6  
2      False                  7  
3      False                  7  
4      False                  7

In [ ]:
y = df_mod['Severity']
y[:5]

0    3
1    3
2    2
3    2
4    2
Name: Severity, dtype: int64

## Splitting

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [ ]:
# x_train[:5]

Zipcode  Temperature  Weekday  Month  Hour   Latitude   Longitude  \
1394997    33169         92.0        5      9    14  25.927330  -80.217706   
1830022    95018         58.0        1      6    20  37.040838 -122.079436   
1240226    92507         84.0        5      5    18  33.951799 -117.303212   
1826552    91761         48.0        6      3     5  34.030476 -117.598324   
657213     33917         84.0        3     10    17  26.684289  -81.872078   

         Humidity  Crossings  Weather_condition  
1394997      45.0      False                  1  
1830022      51.0      False                  1  
1240226      18.0      False                  1  
1826552      74.0      False                  1  
657213       45.0       True                  9

In [ ]:
# y_train[:5]

1394997    2
1830022    2
1240226    2
1826552    2
657213     2
Name: Severity, dtype: int64

In [ ]:
# y_test.shape

## Sampling

In [ ]:
# df_mod['Severity'].value_counts()

Severity
2    3219144
4     106843
3      63728
1      24880
Name: count, dtype: int64

In [ ]:
# 100 * df_mod['Severity'].value_counts() / df_mod.shape[0]

Severity
2    94.276012
4     3.129009
3     1.866341
1     0.728637
Name: count, dtype: float64

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
over_sampler = SMOTE(sampling_strategy='auto', random_state=42)
# sm = SMOTE(random_state = 2)

In [ ]:
# x_train_res, y_train_res = sm.fit_resample(x_train, y_train.ravel())

In [ ]:
from imblearn.under_sampling import RandomUnderSampler

In [ ]:
under_sampler = RandomUnderSampler(sampling_strategy='auto', random_state=42)

In [ ]:
hybrid_sampler = [('over', over_sampler), ('under', under_sampler)]

In [ ]:
from imblearn.pipeline import Pipeline

In [ ]:
hybrid_pipeline = Pipeline(steps=hybrid_sampler)

In [ ]:
# x_hybrid, y_hybrid = hybrid_pipeline.fit_resample(x, y)
# x_hybrid, y_hybrid = hybrid_pipeline.fit_resample(x_train, y_train)
x_train, y_train = hybrid_pipeline.fit_resample(x_train, y_train)

In [ ]:
# x_hybrid.shape

(9013640, 10)

In [ ]:
# y_hybrid.shape

(9013640,)

In [ ]:
# x_hybrid[:5]

Zipcode  Temperature  Weekday  Month  Hour  Latitude  Longitude  \
52     27511         47.0        1      2    20  35.78814  -78.74829   
317    85756        102.0        3      6    18  32.13391 -110.97770   
336    97233         63.0        5      5    12  45.52221 -122.51068   
507    37218         84.0        4      6    14  36.19367  -86.83124   
948    85737         56.0        1      3     6  32.39609 -110.95935   

     Humidity  Crossings  Weather_condition  
52       97.0      False                  6  
317      13.0       True                  1  
336      45.0       True                  0  
507      31.0      False                  1  
948      61.0       True                  0

In [ ]:
# y_hybrid[:5]

52     1
317    1
336    1
507    1
948    1
Name: Severity, dtype: int64

## Machine Learning Models

### → Logistic Regression Classification

In [ ]:
from sklearn.linear_model import LogisticRegression

#### Modeling Logistic Regression Classification

In [ ]:
model_lr = LogisticRegression(max_iter=500)

#### Training Logistic Regression Classification

In [ ]:
model_lr.fit(x_train, y_train)

c:\users\surya\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=500)

#### Prediction Logistic Regression Classification

In [ ]:
y_pred_lr = model_lr.predict(x_test)
y_pred_lr[:5]

array([1, 1, 3, 4, 1], dtype=int64)

#### Evaluation Logistic Regression Classification

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
accuracy_score_lr = accuracy_score(y_test, y_pred_lr)
accuracy_score_lr

0.34357205682662373

In [ ]:
classification_report_lr = classification_report(y_test, y_pred_lr)
print(classification_report_lr)

              precision    recall  f1-score   support

           1       0.01      0.51      0.03      7360
           2       0.97      0.34      0.50    965734
           3       0.05      0.39      0.08     19097
           4       0.05      0.40      0.09     32188

    accuracy                           0.34   1024379
   macro avg       0.27      0.41      0.18   1024379
weighted avg       0.92      0.34      0.48   1024379



#### Pickling Logistic Regression Classification

In [ ]:
import pickle

In [ ]:
model_lr_pkl = pickle.dump(model_lr, open('model_lr.pkl', 'wb'))

### → Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier

#### Modeling Decision Tree Classifier

In [ ]:
model_dt = DecisionTreeClassifier(criterion='entropy', random_state=0)

#### Training Decision Tree Classifier

In [ ]:
model_dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

#### Prediction Decision Tree Classifier

In [ ]:
y_pred_dt = model_dt.predict(x_test)
y_pred_dt[:5]

array([2, 2, 2, 2, 2], dtype=int64)

#### Evaluation Decision Tree Classifier

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
accuracy_score_dt = accuracy_score(y_test, y_pred_dt)
accuracy_score_dt

0.8906928002233548

In [ ]:
classification_report_dt = classification_report(y_test, y_pred_dt)
print(classification_report_dt)

              precision    recall  f1-score   support

           1       0.38      0.59      0.46      7360
           2       0.97      0.92      0.94    965734
           3       0.27      0.48      0.35     19097
           4       0.16      0.28      0.20     32188

    accuracy                           0.89   1024379
   macro avg       0.44      0.57      0.49   1024379
weighted avg       0.92      0.89      0.91   1024379



#### Pickling Decision Tree Classifier

In [ ]:
import pickle

In [ ]:
model_dt_pkl = pickle.dump(model_dt, open('model_dt.pkl', 'wb'))

### → Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

#### Modeling Random Forest Classifier

In [ ]:
model_rf = RandomForestClassifier(n_estimators=150, criterion=
                                  'entropy', random_state=0)

#### Training Random Forest Classifier

In [ ]:
model_rf.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=150, random_state=0)

#### Prediction Random Forest Classifier

In [ ]:
y_pred_rf = model_rf.predict(x_test)
y_pred_rf[:5]

array([2, 2, 2, 2, 2], dtype=int64)

#### Evaluation Random Forest Classifier

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
accuracy_score_rf = accuracy_score(y_test, y_pred_rf)
accuracy_score_rf

0.9243414790814728

In [ ]:
classification_report_rf = classification_report(y_test, y_pred_rf)
print(classification_report_rf)

              precision    recall  f1-score   support

           1       0.51      0.65      0.57      7360
           2       0.97      0.96      0.96    965734
           3       0.45      0.53      0.49     19097
           4       0.25      0.30      0.27     32188

    accuracy                           0.92   1024379
   macro avg       0.55      0.61      0.57   1024379
weighted avg       0.93      0.92      0.93   1024379



#### Pickling Random Forest Classifier

In [ ]:
import pickle

In [ ]:
model_rf_pkl = pickle.dump(model_rf, open('model_rf.pkl', 'wb'))

### → XG Boost RF Classifier

In [ ]:
from xgboost import XGBRFClassifier

#### Modeling XG Boost RF Classifier

In [ ]:
model_xgb = XGBRFClassifier()

#### Label Encoding y_train & y_test
- XGBoostRFClassifier needs values starting from ```0, 1, 2, ...``` for ```y```
- But, here we had values as ```1, 2, 3, 4``` for ```y```
- So, we had to label encode ```y``` values

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lenc = LabelEncoder()

In [ ]:
y_train_xgb = pd.Series(lenc.fit_transform(y_train))

In [ ]:
y_test_xgb = pd.Series(lenc.fit_transform(y_test))

#### Training XG Boost RF Classifier

In [ ]:
model_xgb.fit(x_train, y_train_xgb)

XGBRFClassifier(base_score=None, booster=None, callbacks=None,
                colsample_bylevel=None, colsample_bytree=None,
                early_stopping_rounds=None, enable_categorical=False,
                eval_metric=None, feature_types=None, gamma=None, gpu_id=None,
                grow_policy=None, importance_type=None,
                interaction_constraints=None, max_bin=None,
                max_cat_threshold=None, max_cat_to_onehot=None,
                max_delta_step=None, max_depth=None, max_leaves=None,
                min_child_weight=None, missing=nan, monotone_constraints=None,
                n_estimators=100, n_jobs=None, num_parallel_tree=None,
                objective='multi:softprob', predictor=None, random_state=None,
                reg_alpha=None, ...)

#### Prediction XG Boost RF Classifier

In [ ]:
y_pred_xgb = model_xgb.predict(x_test)
y_pred_xgb[:5]

array([2, 1, 2, 3, 1], dtype=int64)

#### Evaluation XG Boost RF Classifier

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
accuracy_score_xgb = accuracy_score(y_test_xgb, y_pred_xgb)
accuracy_score_xgb

0.5262886099773619

In [ ]:
classification_report_xgb = classification_report(y_test_xgb, y_pred_xgb)
print(classification_report_xgb)

              precision    recall  f1-score   support

           0       0.05      0.81      0.09      7360
           1       0.98      0.53      0.68    965734
           2       0.07      0.63      0.13     19097
           3       0.06      0.40      0.11     32188

    accuracy                           0.53   1024379
   macro avg       0.29      0.59      0.25   1024379
weighted avg       0.93      0.53      0.65   1024379



#### Pickling XG Boost RF Classifier

In [ ]:
import pickle

In [ ]:
model_xgb_pkl = pickle.dump(model_xgb, open('model_xgb.pkl', 'wb'))

### → Gaussian Naive Bayes Classifier

In [ ]:
from sklearn.naive_bayes import GaussianNB

#### Modeling Gaussian NB Classifier

In [ ]:
model_gnb = GaussianNB()

#### Training Gaussian NB Classifier

In [ ]:
model_gnb.fit(x_train, y_train)

GaussianNB()

#### Prediction Gaussian NB Classifier

In [ ]:
y_pred_gnb = model_gnb.predict(x_test)
y_pred_gnb[:5]

array([2, 2, 3, 3, 2], dtype=int64)

#### Evaluation Gaussian NB Classifier

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
accuracy_score_gnb = accuracy_score(y_test, y_pred_gnb)
accuracy_score_gnb

0.3996548152588056

In [ ]:
classification_report_gnb = classification_report(y_test, y_pred_gnb)
print(classification_report_gnb)

              precision    recall  f1-score   support

           1       0.02      0.65      0.05      7360
           2       0.98      0.39      0.56    965734
           3       0.05      0.32      0.09     19097
           4       0.05      0.54      0.10     32188

    accuracy                           0.40   1024379
   macro avg       0.28      0.48      0.20   1024379
weighted avg       0.92      0.40      0.54   1024379



#### Pickling Gaussian NB Classifier

In [ ]:
import pickle

In [ ]:
model_gnb_pkl = pickle.dump(model_gnb, open('model_gnb.pkl', 'wb'))

### → K-Nearest Neighbors Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

#### Modeling K-NN Classifier

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=10)

#### Training K-NN Classifier

In [ ]:
model_knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=10)

#### Prediction K-NN Classifier

In [ ]:
y_pred_knn = model_knn.predict(x_test)
y_pred_knn[:5]

array([2, 2, 3, 2, 3], dtype=int64)

#### Evaluation K-NN Classifier

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
accuracy_score_knn = accuracy_score(y_test, y_pred_knn)
accuracy_score_knn

0.7592453574311852

In [ ]:
classification_report_knn = classification_report(y_test, y_pred_knn)
print(classification_report_knn)

              precision    recall  f1-score   support

           1       0.12      0.69      0.21      7360
           2       0.98      0.77      0.86    965734
           3       0.13      0.56      0.21     19097
           4       0.13      0.57      0.22     32188

    accuracy                           0.76   1024379
   macro avg       0.34      0.65      0.37   1024379
weighted avg       0.93      0.76      0.82   1024379



#### Pickling K-NN Classifier

In [ ]:
import pickle

In [ ]:
model_knn_pkl = pickle.dump(model_knn, open('model_knn.pkl', 'wb'))

### Model Comparison

In [ ]:
accuracy_comparison = pd.DataFrame(['Logistic Regression Classification', 'Decision Tree Classifier', 'Random Forest Classifier', 'XG Boost RF Classifier', 'Gaussian Naive Bayes', 'K-Neighbors Classifier'],
            columns=['Model'])
accuracy_comparison['Accuracy'] =
 [accuracy_score_lr, accuracy_score_dt, accuracy_score_rf, accuracy_score_xgb, accuracy_score_gnb, accuracy_score_knn]
accuracy_comparison.sort_values(by='Accuracy', ascending=False)

Model  Accuracy
2            Random Forest Classifier  0.924341
1            Decision Tree Classifier  0.890693
5              K-Neighbors Classifier  0.759245
3              XG Boost RF Classifier  0.526289
4                Gaussian Naive Bayes  0.399655
0  Logistic Regression Classification  0.343572